version: "3"
services:
  mountebank:
    container_name: mountebank
    image: bbyars/mountebank:latest
    volumes:
    - ./imposters:/imposters
    ports:
    - 2525:2525
    - 8090:8090
    command: mb --configfile /imposters/imposters1.ejs --allowInjection